export const ACTIONSCART = {
  "ADD_TO_CART": "ADD_TO_CART",
  "REMOVE_FROM_CART": "REMOVE_FROM_CART",
  "CLEAR_CART": "CLEAR_CART",
  "UPDATE_CART": "UPDATE_CART",
  "SET_CART": "SET_CART",
  "SET_CART_ITEM_QUANTITY": "SET_CART_ITEM_QUANTITY",
};
